todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('homepage/', include('homepage.urls', namespace='homepage')),
    path('todos/', include('todos.urls', namespace='todos')),
    path('friends/', include('friends.urls', namespace='friends')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_project/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('confirm/<int:pk>/<str:slug>/', views.todo_confirm, name='todo_confirm'),
    path('<int:pk>/<str:slug>/', views.todo_info, name='todo_info'),
    path('add/', views.todo_add, name='todo_add'),
    path('delete/<int:pk>/<str:slug>/', views.todo_del, name='todo_del'),
    path('edit/<int:pk>/<str:slug>/', views.todo_edit, name='todo_edit'),
    path('report/add/<int:pk>/<str:slug>/', views.report_add, name='report_add'),
    path('report/edit/<int:pk>/<str:slug>/', views.report_edit, name='report_edit'),
    path('friends_remind/<int:pk>/<str:username>/', views.friend_reminder, name='friend_reminder'),
    path('friends_remind/', views.friends_reminder, name='friends_reminder'),

    
]

todo_project/todos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Todo(models.Model):
    class StatusChoises(models.TextChoices):
        no_report = 'no_report'
        no_confirm = 'no_confirm'
        confirmed = 'confirmed'
    user = models.ForeignKey(User, related_name='todo', on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    description = models.TextField(max_length=560)
    img = models.ImageField(upload_to='todo_images/', blank=True, null=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=StatusChoises, default=StatusChoises.no_report)

    class Meta:
        ordering = ['publish_date',]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('todos:todo_info', kwargs={'pk': self.pk,
                                     'slug': self.slug,
                                     })
    
    def get_user_absilute_url(self):
        userproxy = UserProxy.objects.get(username=self.user.username)
        return userproxy.get_absolute_url()
    
    



class TodoReport(models.Model):
    todo = models.OneToOneField(Todo, related_name='report', on_delete=models.CASCADE)
    description = models.TextField()
    img = models.ImageField(upload_to='todo_images/report', blank=True, null=True)

todo_project/todos/forms.py
from django import forms


class TodoAddAndEditForm(forms.Form):
    name = forms.CharField(max_length=64)
    description = forms.CharField(widget=forms.Textarea)


class ReportAddForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea)

todo_project/todos/views.py
from django.shortcuts import render,redirect
from .forms import TodoAddAndEditForm, ReportAddForm
from django.urls import reverse
from . import services
from django.contrib.auth.decorators import login_required
from datetime import datetime
from account.services import get_user_by_pk_username



@login_required
def todo_info(request, pk, slug):

    '''подробная иформация о ToDo'''

    current_todo = services.get_todo_by_pk_slug(pk, slug)
    is_user_todo = False
    if current_todo in request.user.todo.all():
        is_user_todo = True
    return render(request, 'todo_info.html', {'current_todo': current_todo, 'is_user_todo': is_user_todo})


@login_required
def todo_add(request):

    '''создание ToDo'''

    user = request.user
    if request.method == 'POST':
        form = TodoAddAndEditForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            services.todo_add(cd, user)
            return redirect(reverse('account:profile_info'))
    else:
        form = TodoAddAndEditForm()
    return render(request, 'todo_add.html', {'form': form})


@login_required
def todo_del(request, pk, slug):

    '''удаление ToDo'''

    services.todo_del(pk, slug)
    return redirect(reverse('account:profile_info'))


@login_required
def todo_edit(request, pk, slug):

    '''изсенение ToDo'''

    todo_to_edit = services.get_todo_by_pk_slug(pk, slug)
    if request.method == 'POST':
        form = TodoAddAndEditForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            services.todo_update(pk, slug, cd)

            return redirect(reverse('todos:todo_info', kwargs={'pk': pk,
                                                                'slug': slug}))
    else:
        form = TodoAddAndEditForm(initial={'name': todo_to_edit.name,
                                            'description': todo_to_edit.description})
    return render(request, 'todo_edit.html', {'form': form})


@login_required
def report_add(request, pk, slug):

    '''создание отчета'''

    current_todo = services.get_todo_by_pk_slug(pk, slug)
    if request.method == 'POST':
        form = ReportAddForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            services.report_add(pk, slug, cd)
            services.todo_change_status(pk, slug, status='no_confirm')
            
            return redirect(current_todo.get_absolute_url())
    else:
        form = ReportAddForm()
    return render(request, 'report_add.html', {'form': form})


@login_required
def report_edit(request, pk, slug):

    '''изменение отчета'''

    current_todo = services.get_todo_by_pk_slug(pk, slug)
    if request.method == 'POST':
        form = ReportAddForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            services.report_edit(pk, slug, cd)
            return redirect(current_todo.get_absolute_url())
    else:
        form = ReportAddForm(initial={'description': current_todo.report.description })
    return render(request, 'report_add.html', {'form': form})


@login_required
def todo_confirm(requset, pk, slug):

    '''подтверждение ToDo и отправка письма о подтверждении'''

    todo = services.todo_change_status(pk, slug, status='confirmed')
    services.your_todo_has_confirmed_mail(todo.user.email,
                                          todo.user.username,
                                          todo.name)
    return redirect(todo.get_absolute_url())


@login_required
def friends_reminder(request):

    '''отправка писем всем друзьям пользователя с просьбой создать ToDO'''

    user = request.user
    friends = services.get_user_friends(user)
    services.friends_reminder_mail(user, friends)
    emails_amount = friends.count()
    now = datetime.now()
    return render(request, 'friends_reminder.html', {'emails_amount': emails_amount, 'now': now})

@login_required
def friend_reminder(request, pk, username):

    '''отправка письма конкретному другу с просьбой создать ToDO'''

    user = request.user
    friend = get_user_by_pk_username(pk, username)
    services.friends_reminder_mail(user, [friend.email])
    now = datetime.now()
    return render(request, 'friends_reminder.html', {'now': now})

todo_project/todos/templates/friends_reminder.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Добавить отчет{% endblock %}

{% block content %}

<div class="d-flex flex-wrap">
    <div class="col offset-3">
        <div class="card m-4" style="width: 50rem; height: 40rem; border-color: #104911;">
            <div class="card-header fw-bold" style="background-color: #104911;  height: 3rem; color: white;">system</div>
            
            <div class="card-body" style="background-color: #ffffff;">
                <h1 class="card-title">
                    Письма отправлены
                </h1>
                <p class="card-text fs-2">Отправили письмо {{ emails_amount }} вашим друзьям с просьбой создать новые ToDO! </p>
            </div>
            <div class="card-footer text-muted">
                {{ now }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo_project/todos/templates/report_add.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Добавить отчет{% endblock %}

{% block content %}

<div class="contaner text-center">
    <h1 style="margin: 3rem;">
        Создайте отчет
    </h1>
</div>


<div class="col-8 offset-2">
    <div class="card shadow p-3 mb-5 " style="background-color: #DECBB7; border-color: #DECBB7;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col mt-1">
                        {% bootstrap_label "отчет" label_for="description" label_class='form-label fw-bold' %}
                        {% bootstrap_field form.description show_label=False  %}
                    </div>
                </div>

                <div class="row text-center mt-4">
                    {% bootstrap_form_errors form layout='inline' %}
                </div>
                <div class="row text-center">
                    <div class="col mt-4">
                        {% bootstrap_button "создать" button_type="submit" size='lg' extra_classes='form-btn-primary' %}
                    </div>    
                </div>
            </form>
        </div>
    </div>
</div>



{% endblock %}

todo_project/todos/templates/todo_add.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Добавить задачу{% endblock %}

{% block content %}

<div class="contaner text-center">
    <h1 style="margin: 3rem;">
        Создайте ToDO
    </h1>
</div>


<div class="col-8 offset-2">
    <div class="card shadow p-3 mb-5 " style="background-color: #DECBB7; border-color: #DECBB7;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col mt-1">
                        {% bootstrap_label "Название" label_for="name" label_class='form-label fw-bold' %}
                        {% bootstrap_field form.name show_label=False  %}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        {% bootstrap_label "Описание" label_for="description" label_class='form-label fw-bold' %}      
                        {% bootstrap_field form.description show_label=False %}
                    </div>
                </div>
                <div class="row text-center mt-4">
                    {% bootstrap_form_errors form layout='inline' %}
                </div>
                <div class="row text-center">
                    <div class="col mt-4">
                        {% bootstrap_button "создать" button_type="submit" size='lg' extra_classes='form-btn-primary' %}
                    </div>    
                </div>
            </form>
        </div>
    </div>
</div>




{% endblock %}

todo_project/todos/templates/todo_edit.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Изменить задачу{% endblock %}

{% block content %}

<div class="contaner text-center">
    <h1 style="margin: 3rem;">
        Измените ToDO
    </h1>
</div>


<div class="col-8 offset-2">
    <div class="card shadow p-3 mb-5 " style="background-color: #DECBB7; border-color: #DECBB7;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col mt-1">
                        {% bootstrap_label "Название" label_for="name" label_class='form-label fw-bold' %}
                        {% bootstrap_field form.name show_label=False  %}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        {% bootstrap_label "Описание" label_for="description" label_class='form-label fw-bold' %}      
                        {% bootstrap_field form.description show_label=False %}
                    </div>
                </div>
                <div class="row text-center mt-4">
                    {% bootstrap_form_errors form layout='inline' %}
                </div>
                <div class="row text-center">
                    <div class="col mt-4">
                        {% bootstrap_button "создать" button_type="submit" size='lg' extra_classes='form-btn-primary' %}
                    </div>    
                </div>
            </form>
        </div>
    </div>
</div>




{% endblock %}

todo_project/todos/templates/todo_info.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}ToDO{% endblock %}

{% block content %}

<div class="row">
    <div class="col-10 offset-md-1 gy-5">
            {% with current_todo as todo %}
                {% if todo.status == 'no_report' %}
                <div class="card m-4" style="border-color: #A22522; ">
                    <div class="card-header fw-bold" style="background-color: #A22522;">
                
                {% elif todo.status == 'no_confirm' %}
                <div class="card m-4" style="border-color: #033F63;">
                    <div class="card-header fw-bold" style="background-color: #033F63;">
                    
                {% elif todo.status == 'confirmed' %}
                <div class="card m-4" style="border-color: #104911;">
                    <div class="card-header fw-bold" style="background-color: #104911;">
                {% endif %}
                        <h2 style="color: white;">{{ todo.user.username }}</h2>
                    </div>
                    <div class="card-body" style="background-color: #ffffff;">
                        <h5 class="card-title fs-1 m-3">
                            <p>{{ todo.name }}</p>
                        </h5>
                        <p class="card-text fs-2" style="margin-left: 2rem;">{{ todo.description }}</p>
                    </div>
                    {% if is_user_todo %} 
                        <div class="row mb-4">
                            <div class="col">
                                <span style="margin-left: 2rem;">
                                    <a href="{% url 'todos:todo_edit' todo.pk todo.slug %}" class="btn btn-primary btn-lg" style="background-color: #DECBB7; border-color: #DECBB7; color: black;">изменить</a>
                                    <a href="{% url 'todos:todo_del' todo.pk todo.slug %}" class="btn btn-primary btn-lg" style="background-color: #972D07; border-color: #972D07; color: black;">удалить</a>
                                </span>                                    
                            </div>
                            <div class="col offset-6">
                                {% if todo.status == 'no_report' %}
                                <a href="{% url 'todos:report_add' todo.pk todo.slug %}" class="btn btn-primary btn-lg" style="background-color: #DECBB7; border-color: #DECBB7; color: black;">создать отчет</a>
                                {% endif %}
                                
                            </div>
                        </div>

                        
                    {% endif %}

                    {% if todo.report %}
                        <ul class="list-group list-group-flush">
                            <h3 class="m-4">Отчет</h3>
                            <li class="list-group-item fs-2" style="margin-left: 2rem;">{{ todo.report.description }}
                            <div class="row mt-3">
                                <div class="col-3">
                                    {% if is_user_todo == False and todo.status == 'no_confirm' %}
                                        <a href="{% url 'todos:todo_confirm' todo.pk todo.slug %}" class="btn btn-primary btn-lg" style="background-color: #DECBB7; border-color: #DECBB7; color: black;">Подтвердить отчет</a>
                                    {% endif %}
                                </div>
                                
                            </div>
                            

                            </li>
                        </ul>
                        
                    {% endif %}
                    <div class="card-footer text-muted mt-4">
                        {{ todo.publish_date }}
                    </div>
                </div>
            {% endwith %}
                </div>

    </div>
</div>



{% endblock %}