todo_project/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),

]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('homepage/', include('homepage.urls', namespace='homepage')),
    path('todos/', include('todos.urls', namespace='todos')),
    path('friends/', include('friends.urls', namespace='friends')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_project/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('confirm/<int:pk>/<str:slug>/', views.todo_confirm, name='todo_confirm'),
    path('<int:pk>/<str:slug>/', views.todo_info, name='todo_info'),
    path('add/', views.todo_add, name='todo_add'),
    path('delete/<int:pk>/<str:slug>/', views.todo_del, name='todo_del'),
    path('edit/<int:pk>/<str:slug>/', views.todo_edit, name='todo_edit'),
    path('report/add/<int:pk>/<str:slug>/', views.report_add, name='report_add'),
    path('report/edit/<int:pk>/<str:slug>/', views.report_edit, name='report_edit'),
    path('friends_remind/<int:pk>/<str:username>/', views.friend_reminder, name='friend_reminder'),
    path('friends_remind/', views.friends_reminder, name='friends_reminder'),

    
]

todo_project/homepage/models.py
from django.db import models

# Create your models here.

todo_project/homepage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import services
from datetime import datetime


@login_required
def homepage(requset):

    '''отображения главной страницы с собстенными ToDo и ToDo друзей'''

    user = requset.user
    user_todos = services.get_user_todos(user)
    friends_todos = services.get_friends_todos(user)
    now = datetime.now()
    return render(requset, 'homepage/homepage.html', {'user_todos': user_todos, 'friends_todos': friends_todos, 'now': now})

todo_project/homepage/templates/homepage/homepage.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}домашнаяя страница{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-8">
            <div class="d-flex flex-wrap justify-content-start">
            {% for todo in friends_todos %}
                    {% if todo.status == 'no_report' %}
                    <div class="card m-4" style="width: 20rem; height: 15rem; border-color: #A22522; ">
                        <div class="card-header fw-bold" style="background-color: #A22522;">
                    
                    {% elif todo.status == 'no_confirm' %}
                    <div class="card m-4" style="width: 20rem; height: 15rem; border-color: #033F63;">
                        <div class="card-header fw-bold" style="background-color: #033F63;">
                        
                    {% elif todo.status == 'confirmed' %}
                    <div class="card m-4" style="width: 20rem; height: 15rem; border-color: #104911;">
                        <div class="card-header fw-bold" style="background-color: #104911;">
                    {% endif %}
                                <a href="{{ todo.get_user_absolute_url }}" class="text-decoration-none" style="color: white;">{{ todo.user.username }}</a>
                        </div>
                        <div class="card-body" style="background-color: #ffffff;">
                            <h5 class="card-title">
                                <a href="{{ todo.get_absolute_url }}" class="text-decoration-none">{{ todo.name }}</a>
                            </h5>
                            <p class="card-text">{{ todo.description|truncatechars:100 }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ todo.publish_date }}
                        </div>
                    </div>
            {% empty %}
                <div class="d-flex flex-wrap">
                    <div class="col offset-3">
                        <div class="card m-4" style="width: 50rem; height: 40rem; border-color: #104911;">
                            <div class="card-header fw-bold" style="background-color: #104911;  height: 3rem; color: white;">system</div>
                            
                            <div class="card-body" style="background-color: #ffffff;">
                                <h1 class="card-title">
                                    У ваших друзей нет ToDO...
                                </h1>
                                <p class="card-text fs-2">Может <span><a href="{% url 'todos:friends_reminder' %}" class="text-decoration-none">напомнить</a></span> о создании задач на сегодня?</p>
                            </div>
                            <div class="card-footer text-muted">
                                {{ now }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="col-4">
            <div class="card m-4" style="border-color: black;">
                <div class="card-header fw-bold"><h4>Ваши ToDO на сегодня</h4></div>
                <ul class="list-group listgroup-flush">
                {% for todo in user_todos %}
                        <li class="list-group-item text-center">
                            <a href="{{ todo.get_abcolute_url }}" class="text-decoration-none" style="color: black;">
                                <h3 class="fw-normal fst-italic text-decoration-underline"> -{{ todo.name }}</h3>
                            </a>
                        </li>
                
                {% empty %}
                <div style="margin: 2rem;">
                    <h3 class="fw-normal" style="margin-left: 2 rem;">У вас нет ToDO на сегодня</h3>
                </div>   
                 
                {% endfor %}
                <div class="card-footer">
                    <a href="{% url 'todos:todo_add' %}" class="text-decoration-none">Создать еще?</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}