todo_project/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('reset/<int:pk>/<str:token>/', views.reset_password_proccess, name='reset_password_proccess'),
    path('frorgot_password/', views.forgot_password, name='forgot_password'),
    path('password_reset/', views.reset_password_email, name='reset_password_email'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('profile_info/', views.profile_info, name='profile_info'),
    path('profile_info_edit/', views.profile_info_edit, name='profile_info_edit'),
    path('<int:pk>/<str:username>/', views.another_profile_info, name='another_profile_info'),
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('homepage/', include('homepage.urls', namespace='homepage')),
    path('todos/', include('todos.urls', namespace='todos')),
    path('friends/', include('friends.urls', namespace='friends')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_project/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('confirm/<int:pk>/<str:slug>/', views.todo_confirm, name='todo_confirm'),
    path('<int:pk>/<str:slug>/', views.todo_info, name='todo_info'),
    path('add/', views.todo_add, name='todo_add'),
    path('delete/<int:pk>/<str:slug>/', views.todo_del, name='todo_del'),
    path('edit/<int:pk>/<str:slug>/', views.todo_edit, name='todo_edit'),
    path('report/add/<int:pk>/<str:slug>/', views.report_add, name='report_add'),
    path('report/edit/<int:pk>/<str:slug>/', views.report_edit, name='report_edit'),
    path('friends_remind/<int:pk>/<str:username>/', views.friend_reminder, name='friend_reminder'),
    path('friends_remind/', views.friends_reminder, name='friends_reminder'),

    
]

todo_project/account/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.urls import reverse
from todos.models import Todo

class Profile(models.Model):
    class SexChoises(models.TextChoices):
        male = 'М'
        female = 'Ж'
        default = '-'  

    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    sex = models.CharField(max_length=1, choices=SexChoises, default=SexChoises.default)
    birthd = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='user_images/', blank=True, null=True)
    preview = models.TextField(blank=True)
    friends = models.ManyToManyField('self', through='friends.Friendship', symmetrical=True)

    class Meta:
        ordering = ['birthd']

    def get_age(self):
        days = (datetime.datetime.now() - self.birthd).days
        return days // 365
    



class UserProxy(User):

    class Meta:
        proxy = True

    def get_absolute_url(self):
        return reverse('account:another_profile_info', kwargs={'pk': self.pk,
                                                              'username': self.username})
    
    def get_number_todos_status(self, status):
        return Todo.objects.filter(user=self, status=status).count()
    


    

todo_project/account/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(label='логин')
    email = forms.EmailField(label='почта')
    password1 = forms.CharField(label='пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='повторите пароль', widget=forms.PasswordInput)


    def clean_username(self):
        data = self.cleaned_data['username']
        try:
            User.objects.get(username=data)
            raise ValidationError('имя пользователя занято')
        except User.DoesNotExist:
            return data
        
    def clean_email(self):
        data = self.cleaned_data['email']
        try:
            User.objects.get(email=data)
            raise ValidationError('аккаунт с данной почтой существует')
        except User.DoesNotExist:
            return data

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 != password2:
            raise ValidationError('Пароли не совпадают')




class LoginForm(forms.Form):
    username = forms.CharField(label='логин')
    password = forms.CharField(label='пароль', widget=forms.PasswordInput)



class ProfileInfoForm(forms.Form):
    username = forms.CharField(label='логин')
    email = forms.EmailField(label='почта')
    birthd = forms.DateField(label='дата рождения')
    sex = forms.ChoiceField(choices=[('male','м'), ('female','ж')])
    photo = forms.ImageField(required=False)
    preview = forms.CharField(widget=forms.Textarea)





class ResetPasswordForm(forms.Form):
    password1 = forms.CharField(label='пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='повторите пароль', widget=forms.PasswordInput)

class FortgotPasswordForm(forms.Form):
    email = forms.EmailField(label='почта привязанная к аккаунту')

    def clean_email(self):
        user_email = self.cleaned_data['email']
        try:
            User.objects.get(email=user_email)
            return user_email
        except User.DoesNotExist:
            raise ValidationError('аккаунта с данной почтой не существует')




  

todo_project/account/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import RegisterForm, LoginForm, ProfileInfoForm, ResetPasswordForm, FortgotPasswordForm
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from . import services
from django.contrib.auth.models import User
from datetime import datetime
import sys
sys.path.append('..')



def login_view(request):

    '''вход пользователя в аккаунт'''

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = services.user_auth(cd)
            if user:
                services.user_login(request, user)
                return redirect('/homepage')
            else:
                form.add_error(field=None, error=ValidationError('неверный логин или пароль'))
    else:
        form = LoginForm()
    return render(request, 'authentication/login.html', {'form': form})


@login_required
def logout_view(request):
    services.user_logout(request)
    return redirect(reverse('account:login'))



def register_view(request):
    '''регистарция пользователя, создание экземпляра User и связанного с ним Profile'''
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            services.user_register(cd)
            return redirect('/account/login')
    else:
        form = RegisterForm()
    return render(request, 'authentication/register.html', {'form': form})


@login_required
def profile_info(request):
    '''страница с информацией профиля'''
    user = request.user
    user_todos = services.get_user_todos(user)
    return render(request, 'account/profile_info.html', {'user': user, 'user_todos': user_todos})



@login_required
def profile_info_edit(request):
    '''страница для изменения информации об аккаунте'''
    user = request.user
    if request.method == 'POST':
        form = ProfileInfoForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data 
            error_dict = {}
            error_dict['username'] = User.objects.exclude(pk=user.pk).filter(username=cd['username'])
            error_dict['email'] =  User.objects.exclude(pk=user.pk).filter(email=cd['email'])
            if len(error_dict['username']) == 0 and len(error_dict['email']) == 0:
                services.user_profile_update_user_model(request, cd)
                services.user_profile_update_profile_model(request, cd)
                return redirect('/account/profile_info')
            else:
                if len(error_dict['username']) != 0:
                    form.add_error(field='username', error=ValidationError('Логин уже занят'))
                elif len(error_dict['email']) != 0:
                    form.add_error(field='email', error=ValidationError('Почта уже привязана к другому аккаунту'))

        
    else:
        form = ProfileInfoForm(initial={
            'username': user.username,
            'email': user.email,
            'birthd': user.profile.birthd,
            'sex': user.profile.sex,
            'preview': user.profile.preview,
            'photo': user.profile.photo,
        })
                                        
    return render(request, 'account/profile_info_edit.html', {'form': form})


@login_required
def another_profile_info(request, pk, username):
    '''профиль другого пользователя, его ToDo, и проверка является ли он другом текущего пользователя'''   
    user = services.get_user_by_pk_username(pk, username)
    friend_add_flag = True
    if user.profile in services.get_user_friends(request.user):
        friend_add_flag = False
    user_todos = services.get_user_todos(user)
    return render(request, 'account/another_profile_info.html', {'user': user, 'user_todos': user_todos, 'friend_add_flag': friend_add_flag})


@login_required
def reset_password_email(request):

    '''метод для вошедшего пользователя: отправка письма с токеном'''
    
    token = services.make_token(request.user)
    services.reset_password_email(request.user, token)
    now = datetime.now()
    return render(request, 'account/reset_email_sent.html', {'now': now})


def reset_password_proccess(request, pk, token):
    '''смена пароля и обработка перехода по устаревшему токену'''
    now = datetime.now()
    user = services.get_user_by_pk(pk=pk)
    if request.method == 'POST':
        checker = PasswordResetTokenGenerator()
        if checker.check_token(user=user, token=token):
            form = ResetPasswordForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user.set_password(cd['password1'])
                user.save()
                return render(request, 'account/reset_password_success.html', {'now': now})
            
    else:

        checker = PasswordResetTokenGenerator()
        if checker.check_token(user=user, token=token):
            form = ResetPasswordForm()
            return render(request, 'account/reset_password_get.html', {'form': form, 'now': now})
    return render(request, 'account/reset_password_token_fail.html', {'now': now})


def forgot_password(request):

    '''метод для не вошедшего пользователя: отправка письма с токеном'''

    if request.method == 'POST':
        form = FortgotPasswordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = services.get_user_by_email(cd['email'])
            token = services.make_token(user)
            services.reset_password_email(user, token)
            return render(request, 'account/reset_email_sent.html')
    else:
        form = FortgotPasswordForm()
    return render(request, 'account/forgot_password.html', {'form': form})

todo_project/account/templates/authentication/login.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Войти{% endblock %}

{% block content %}

<div class="container">
    <div class="col-4 offset-md-4">
        <h1 class="offset-md-4 mt-5 mb-3">TODO</h1>
        <div class="card shadow p-3 mb-5 " style="background-color: #DECBB7; border-color: #DECBB7;">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col mt-1">
                            {% bootstrap_label "Логин" label_for="username" label_class='form-label fw-bold' %}
                            {% bootstrap_field form.username show_label=False  %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {% bootstrap_label "Пароль" label_for="password" label_class='form-label fw-bold' %}
                            
                            {% bootstrap_field form.password show_label=False %}
                            <a class="fs-6 text-decoration-none" href="{% url 'account:forgot_password' %}">Забыли пароль?</a>
                        </div>
                    </div>
                    <div class="row text-center mt-4">
                        {% bootstrap_form_errors form layout='inline' %}
                    </div>
                    <div class="row text-center">
                        <div class="col mt-4">
                            {% bootstrap_button "войти" button_type="submit" size='lg' extra_classes='form-btn-primary' %}
                        </div>    
                    </div>
                </form>
            </div>
        </div>
        <h6 class="fw-normal">Нет аккаунтa? <a href="{% url 'account:register' %}" class="text-decoration-none">Зарегистрироватья в ToDO</a></h6>
    </div>
</div>

{% endblock %}

todo_project/account/templates/authentication/register.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
    <div class="col-4 offset-md-4">
        <h1 class="offset-md-4 mt-5 mb-3">TODO</h1>
        <div class="card shadow p-3 mb-5 " style="background-color: #DECBB7; border-color: #DECBB7;">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col mt-1">
                            {% bootstrap_label "Логин" label_for="username" label_class='form-label fw-bold' %}
                            {% bootstrap_field form.username show_label=False  %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {% bootstrap_label "Почта" label_for="email" label_class='form-label fw-bold' %}
                            {% bootstrap_field form.email show_label=False %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {% bootstrap_label "Пароль" label_for="password1" label_class='form-label fw-bold' %}
                            {% bootstrap_field form.password1 show_label=False %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {% bootstrap_label "Подтвердите пароль" label_for="password2" label_class='form-label fw-bold' %}
                            {% bootstrap_field form.password2 show_label=False %}
                        </div>
                    </div>

                    <div class="row text-center mt-4">
                        {% bootstrap_form_errors form layout='inline' %}
                    </div>
                    <div class="row text-center">
                        <div class="col mt-4">
                            {% bootstrap_button "зарегестрироваться" button_type="submit" size='lg' extra_classes='form-btn-primary' %}
                        </div>    
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}